-- How fast an engine answered, one row per game, reported by the client that
-- ran it. The hosted node publishes its own timings to Prometheus; nothing
-- measured the engines that run on a player's machine, offline play least of
-- all, because no server is in the loop there.
--
-- Aggregates only: percentiles, counts and how the game ended. No deck, no
-- card, no opponent, nothing that identifies a player. `id` is generated by
-- the client so a retry cannot double-count a game.
CREATE TABLE engine_play_stats (
    id              TEXT PRIMARY KEY,
    reported_at     TEXT NOT NULL,
    engine          TEXT NOT NULL,
    client_version  TEXT NOT NULL,
    platform        TEXT NOT NULL,
    format          TEXT,
    seats           INTEGER NOT NULL,
    multiplayer     INTEGER NOT NULL,
    duration_s      INTEGER NOT NULL,
    end_reason      TEXT NOT NULL,
    decisions       INTEGER NOT NULL,
    turnaround_p50  INTEGER NOT NULL,
    turnaround_p90  INTEGER NOT NULL,
    turnaround_max  INTEGER NOT NULL,
    engine_p50      INTEGER,
    engine_p90      INTEGER,
    engine_max      INTEGER,
    by_type         TEXT NOT NULL
);

-- The two questions this table exists to answer: how an engine performs over
-- time, and how two engines compare on the same day.
CREATE INDEX idx_engine_play_stats_engine_time ON engine_play_stats(engine, reported_at);
