function audioAsset(name: string) {
  return { alias: `display-event-audio.${name}`, src: `/sounds/${name}.wav` } as const;
}

export const DISPLAY_EVENT_AUDIO_ASSETS = {
  gameStart: audioAsset("game-start"),
  turnStart: audioAsset("turn-start"),
  cardPlay: audioAsset("card-play"),
  cardDraw: audioAsset("card-draw"),
  cardTap: audioAsset("card-tap"),
  cardUntap: audioAsset("card-untap"),
  cardDiscard: audioAsset("card-discard"),
  cardDestroy: audioAsset("card-destroy"),
  cardExile: audioAsset("card-exile"),
  shuffle: audioAsset("shuffle"),
  lifeGain: audioAsset("life-gain"),
  lifeLoss: audioAsset("life-loss"),
  diceRoll: audioAsset("dice-roll"),
  prompt: audioAsset("prompt"),
  error: audioAsset("error"),
  counterAdd: audioAsset("counter-add"),
  combatBlock: audioAsset("combat-block"),
  cardDamage: audioAsset("card-damage"),
  daytime: audioAsset("daytime"),
  turnEnd: audioAsset("turn-end"),
  cardAttach: audioAsset("card-attach"),
  cardTransform: audioAsset("card-transform"),
  coinFlip: audioAsset("coin-flip"),
  gameLoss: audioAsset("game-loss"),
  manaBurn: audioAsset("mana-burn"),
  nighttime: audioAsset("nighttime"),
  cardPhase: audioAsset("card-phase"),
  poison: audioAsset("poison"),
  cardRegenerate: audioAsset("card-regenerate"),
  counterRemove: audioAsset("counter-remove"),
  cardSacrifice: audioAsset("card-sacrifice"),
  snapshotRestored: audioAsset("snapshot-restored"),
  speedUp: audioAsset("speed-up"),
  sprocket: audioAsset("sprocket"),
  playerShard: audioAsset("player-shard"),
  tokenCreate: audioAsset("token-create"),
  gameWin: audioAsset("game-win"),
  spellArtifact: audioAsset("spell-artifact"),
  spellArtifactCreature: audioAsset("spell-artifact-creature"),
  spellCreature: audioAsset("spell-creature"),
  spellEnchantment: audioAsset("spell-enchantment"),
  spellInstant: audioAsset("spell-instant"),
  spellPlaneswalker: audioAsset("spell-planeswalker"),
  spellSorcery: audioAsset("spell-sorcery"),
  landBlack: audioAsset("land-black"),
  landBlue: audioAsset("land-blue"),
  landGreen: audioAsset("land-green"),
  landRed: audioAsset("land-red"),
  landWhite: audioAsset("land-white"),
  landBlackRed: audioAsset("land-black-red"),
  landBlackWhite: audioAsset("land-black-white"),
  landBlueBlack: audioAsset("land-blue-black"),
  landGreenBlack: audioAsset("land-green-black"),
  landGreenBlue: audioAsset("land-green-blue"),
  landGreenRed: audioAsset("land-green-red"),
  landRedBlue: audioAsset("land-red-blue"),
  landWhiteBlue: audioAsset("land-white-blue"),
  landWhiteGreen: audioAsset("land-white-green"),
  landWhiteRed: audioAsset("land-white-red"),
  landBlackRedGreen: audioAsset("land-black-red-green"),
  landBlackWhiteGreen: audioAsset("land-black-white-green"),
  landBlueBlackRed: audioAsset("land-blue-black-red"),
  landGreenBlackBlue: audioAsset("land-green-black-blue"),
  landGreenBlueRed: audioAsset("land-green-blue-red"),
  landGreenRedWhite: audioAsset("land-green-red-white"),
  landRedBlueWhite: audioAsset("land-red-blue-white"),
  landWhiteBlueBlack: audioAsset("land-white-blue-black"),
  landWhiteGreenBlue: audioAsset("land-white-green-blue"),
  landWhiteRedBlack: audioAsset("land-white-red-black"),
  landOther: audioAsset("land-other"),
  scriptedEffect: audioAsset("scripted-effect"),
} as const;

export type DisplayEventAudioAssetKey = keyof typeof DISPLAY_EVENT_AUDIO_ASSETS;

export interface DisplayEventAudioDefinition {
  variants: readonly DisplayEventAudioAssetKey[];
  voiceLimit: number;
  cooldownMs: number;
  volume: number;
}

function audio(
  asset: DisplayEventAudioAssetKey,
  voiceLimit: number,
  cooldownMs: number,
  volume: number,
): DisplayEventAudioDefinition {
  return { variants: [asset], voiceLimit, cooldownMs, volume };
}

export const DISPLAY_EVENT_AUDIO: Record<string, DisplayEventAudioDefinition> = {
  "game.card.draw": audio("cardDraw", 4, 40, 0.7),
  "game.card.play": audio("cardPlay", 3, 70, 0.8),
  "game.card.tap": audio("cardTap", 4, 35, 0.65),
  "game.card.untap": audio("cardUntap", 4, 35, 0.65),
  "game.card.discard": audio("cardDiscard", 3, 70, 0.75),
  "game.card.destroy": audio("cardDestroy", 3, 80, 0.8),
  "game.card.exile": audio("cardExile", 3, 80, 0.75),
  "game.library.shuffle": audio("shuffle", 1, 300, 0.65),
  "game.player.life-gain": audio("lifeGain", 3, 80, 0.7),
  "game.player.life-loss": audio("lifeLoss", 3, 80, 0.75),
  "game.turn.start": audio("turnStart", 1, 250, 0.75),
  "game.random.die-roll": audio("diceRoll", 2, 120, 0.7),
  "game.start": audio("gameStart", 1, 500, 0.8),
  "prompt.decision-required": audio("prompt", 1, 250, 0.65),
  "prompt.target-required": audio("prompt", 1, 250, 0.65),
  "prompt.payment-required": audio("prompt", 1, 250, 0.65),
  "prompt.combat-required": audio("prompt", 1, 250, 0.65),
  "prompt.action-rejected": audio("error", 1, 250, 0.75),
  "game.card.counter-add": audio("counterAdd", 3, 70, 0.7),
  "game.combat.block": audio("combatBlock", 3, 70, 0.7),
  "game.card.damage": audio("cardDamage", 3, 70, 0.7),
  "game.day-night.day": audio("daytime", 3, 70, 0.7),
  "game.turn.end": audio("turnEnd", 1, 250, 0.75),
  "game.card.attach": audio("cardAttach", 3, 70, 0.7),
  "game.card.transform": audio("cardTransform", 3, 70, 0.7),
  "game.random.coin-flip": audio("coinFlip", 3, 70, 0.7),
  "game.outcome.loss": audio("gameLoss", 1, 500, 0.8),
  "game.player.mana-burn": audio("manaBurn", 3, 70, 0.7),
  "game.day-night.night": audio("nighttime", 3, 70, 0.7),
  "game.card.phase": audio("cardPhase", 3, 70, 0.7),
  "game.player.poison": audio("poison", 3, 70, 0.7),
  "game.card.regenerate": audio("cardRegenerate", 3, 70, 0.7),
  "game.card.counter-remove": audio("counterRemove", 3, 70, 0.7),
  "game.card.sacrifice": audio("cardSacrifice", 3, 70, 0.7),
  "game.snapshot.restored": audio("snapshotRestored", 1, 250, 0.75),
  "game.player.speed-up": audio("speedUp", 1, 250, 0.75),
  "game.contraption.sprocket": audio("sprocket", 3, 70, 0.7),
  "game.player.shard": audio("playerShard", 3, 70, 0.7),
  "game.token.create": audio("tokenCreate", 3, 70, 0.7),
  "game.outcome.win": audio("gameWin", 1, 500, 0.8),
  "game.spell.resolve.artifact": audio("spellArtifact", 3, 80, 0.75),
  "game.spell.resolve.artifact-creature": audio("spellArtifactCreature", 3, 80, 0.75),
  "game.spell.resolve.creature": audio("spellCreature", 3, 80, 0.75),
  "game.spell.resolve.enchantment": audio("spellEnchantment", 3, 80, 0.75),
  "game.spell.resolve.instant": audio("spellInstant", 3, 80, 0.75),
  "game.spell.resolve.planeswalker": audio("spellPlaneswalker", 3, 80, 0.75),
  "game.spell.resolve.sorcery": audio("spellSorcery", 3, 80, 0.75),
  "game.land.enter.black": audio("landBlack", 3, 70, 0.65),
  "game.land.enter.blue": audio("landBlue", 3, 70, 0.65),
  "game.land.enter.green": audio("landGreen", 3, 70, 0.65),
  "game.land.enter.red": audio("landRed", 3, 70, 0.65),
  "game.land.enter.white": audio("landWhite", 3, 70, 0.65),
  "game.land.enter.black-red": audio("landBlackRed", 3, 70, 0.65),
  "game.land.enter.black-white": audio("landBlackWhite", 3, 70, 0.65),
  "game.land.enter.blue-black": audio("landBlueBlack", 3, 70, 0.65),
  "game.land.enter.green-black": audio("landGreenBlack", 3, 70, 0.65),
  "game.land.enter.green-blue": audio("landGreenBlue", 3, 70, 0.65),
  "game.land.enter.green-red": audio("landGreenRed", 3, 70, 0.65),
  "game.land.enter.red-blue": audio("landRedBlue", 3, 70, 0.65),
  "game.land.enter.white-blue": audio("landWhiteBlue", 3, 70, 0.65),
  "game.land.enter.white-green": audio("landWhiteGreen", 3, 70, 0.65),
  "game.land.enter.white-red": audio("landWhiteRed", 3, 70, 0.65),
  "game.land.enter.black-red-green": audio("landBlackRedGreen", 3, 70, 0.65),
  "game.land.enter.black-white-green": audio("landBlackWhiteGreen", 3, 70, 0.65),
  "game.land.enter.blue-black-red": audio("landBlueBlackRed", 3, 70, 0.65),
  "game.land.enter.green-black-blue": audio("landGreenBlackBlue", 3, 70, 0.65),
  "game.land.enter.green-blue-red": audio("landGreenBlueRed", 3, 70, 0.65),
  "game.land.enter.green-red-white": audio("landGreenRedWhite", 3, 70, 0.65),
  "game.land.enter.red-blue-white": audio("landRedBlueWhite", 3, 70, 0.65),
  "game.land.enter.white-blue-black": audio("landWhiteBlueBlack", 3, 70, 0.65),
  "game.land.enter.white-green-blue": audio("landWhiteGreenBlue", 3, 70, 0.65),
  "game.land.enter.white-red-black": audio("landWhiteRedBlack", 3, 70, 0.65),
  "game.land.enter.other": audio("landOther", 3, 70, 0.65),
  "game.card.scripted-effect": audio("scriptedEffect", 3, 70, 0.7),
};
