function audioAsset(name: string) {
  return { alias: `display-event-audio.${name}`, src: `/sounds/${name}.wav` } as const;
}

export const DISPLAY_EVENT_AUDIO_ASSETS = {
  bookClose: audioAsset("book-close"),
  cardContactFirm: audioAsset("card-contact-firm"),
  cardContactSoft: audioAsset("card-contact-soft"),
  cardCut: audioAsset("card-cut"),
  cardPlay: audioAsset("card-play"),
  coin: audioAsset("coin"),
  gemBright: audioAsset("gem-bright"),
  gemLight: audioAsset("gem-light"),
  metalHeavy: audioAsset("metal-heavy"),
  metalLight: audioAsset("metal-light"),
  pageBrisk: audioAsset("page-brisk"),
  pageSoft: audioAsset("page-soft"),
  pieceHeavy: audioAsset("piece-heavy"),
  shuffle: audioAsset("shuffle"),
  spellBright: audioAsset("spell-bright"),
  spellFire: audioAsset("spell-fire"),
  spellSoft: audioAsset("spell-soft"),
  stoneHeavy: audioAsset("stone-heavy"),
  stoneLight: audioAsset("stone-light"),
  woodHeavy: audioAsset("wood-heavy"),
  woodLight: audioAsset("wood-light"),
  woodMedium: audioAsset("wood-medium"),
  woodenDice: audioAsset("wooden-dice"),
} as const;

export type DisplayEventAudioAssetKey = keyof typeof DISPLAY_EVENT_AUDIO_ASSETS;

export interface DisplayEventAudioDefinition {
  variants: readonly DisplayEventAudioAssetKey[];
  voiceLimit: number;
  cooldownMs: number;
  volume: number;
}

function audio(
  asset: DisplayEventAudioAssetKey,
  voiceLimit: number,
  cooldownMs: number,
  volume: number,
): DisplayEventAudioDefinition {
  return { variants: [asset], voiceLimit, cooldownMs, volume };
}

export const DISPLAY_EVENT_AUDIO: Record<string, DisplayEventAudioDefinition> = {
  "game.card.draw": audio("cardContactSoft", 4, 40, 0.7),
  "game.card.play": audio("cardPlay", 3, 70, 0.8),
  "game.card.tap": audio("woodLight", 4, 35, 0.65),
  "game.card.untap": audio("cardContactFirm", 4, 35, 0.65),
  "game.card.discard": audio("cardCut", 3, 70, 0.75),
  "game.card.destroy": audio("woodHeavy", 3, 80, 0.8),
  "game.card.exile": audio("pageBrisk", 3, 80, 0.75),
  "game.library.shuffle": audio("shuffle", 1, 300, 0.65),
  "game.player.life-gain": audio("gemBright", 3, 80, 0.7),
  "game.player.life-loss": audio("stoneHeavy", 3, 80, 0.75),
  "game.turn.start": audio("gemLight", 1, 250, 0.75),
  "game.random.die-roll": audio("woodenDice", 2, 120, 0.7),
  "game.start": audio("bookClose", 1, 500, 0.8),
  "prompt.decision-required": audio("gemLight", 1, 250, 0.65),
  "prompt.target-required": audio("gemLight", 1, 250, 0.65),
  "prompt.payment-required": audio("gemLight", 1, 250, 0.65),
  "prompt.combat-required": audio("gemLight", 1, 250, 0.65),
  "prompt.action-rejected": audio("stoneLight", 1, 250, 0.75),
  "game.card.counter-add": audio("cardContactSoft", 3, 70, 0.7),
  "game.combat.block": audio("woodMedium", 3, 70, 0.7),
  "game.card.damage": audio("woodHeavy", 3, 70, 0.7),
  "game.day-night.day": audio("pageSoft", 3, 70, 0.7),
  "game.turn.end": audio("cardCut", 1, 250, 0.75),
  "game.card.attach": audio("metalLight", 3, 70, 0.7),
  "game.card.transform": audio("pageBrisk", 3, 70, 0.7),
  "game.random.coin-flip": audio("coin", 3, 70, 0.7),
  "game.outcome.loss": audio("stoneHeavy", 1, 500, 0.8),
  "game.player.mana-burn": audio("spellFire", 3, 70, 0.7),
  "game.day-night.night": audio("bookClose", 3, 70, 0.7),
  "game.card.phase": audio("pageSoft", 3, 70, 0.7),
  "game.player.poison": audio("stoneLight", 3, 70, 0.7),
  "game.card.regenerate": audio("spellSoft", 3, 70, 0.7),
  "game.card.counter-remove": audio("cardContactFirm", 3, 70, 0.7),
  "game.card.sacrifice": audio("woodHeavy", 3, 70, 0.7),
  "game.snapshot.restored": audio("pageSoft", 1, 250, 0.75),
  "game.player.speed-up": audio("cardCut", 1, 250, 0.75),
  "game.contraption.sprocket": audio("metalHeavy", 3, 70, 0.7),
  "game.player.shard": audio("gemBright", 3, 70, 0.7),
  "game.token.create": audio("pieceHeavy", 3, 70, 0.7),
  "game.outcome.win": audio("coin", 1, 500, 0.8),
  "game.spell.resolve.artifact": audio("metalLight", 3, 80, 0.75),
  "game.spell.resolve.artifact-creature": audio("metalHeavy", 3, 80, 0.75),
  "game.spell.resolve.creature": audio("pieceHeavy", 3, 80, 0.75),
  "game.spell.resolve.enchantment": audio("spellSoft", 3, 80, 0.75),
  "game.spell.resolve.instant": audio("spellBright", 3, 80, 0.75),
  "game.spell.resolve.planeswalker": audio("gemBright", 3, 80, 0.75),
  "game.spell.resolve.sorcery": audio("spellFire", 3, 80, 0.75),
  "game.land.enter.black": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.black-red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.black-white": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.blue-black": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-black": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.red-blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-green": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.black-red-green": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.black-white-green": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.blue-black-red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-black-blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-blue-red": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.green-red-white": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.red-blue-white": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-blue-black": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-green-blue": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.white-red-black": audio("cardContactFirm", 3, 70, 0.65),
  "game.land.enter.other": audio("cardContactFirm", 3, 70, 0.65),
  "game.card.scripted-effect": audio("spellBright", 3, 70, 0.7),
};
