import type { CardDto } from "@/protocol/game";

export const GAME_CARD_DEFAULTS: CardDto = {
  id: "",
  name: "",
  setCode: "",
  cardNumber: "",
  color: "",
  manaCost: "",
  cmc: 0,
  types: [],
  subtypes: [],
  supertypes: [],
  power: null,
  toughness: null,
  text: "",
  controllerId: "",
  ownerId: "",
  zoneId: "",
  tapped: false,
  isCrewed: false,
  isAttacking: false,
  keywords: [],
  counters: {},
  damage: 0,
  summoningSick: false,
  isToken: false,
  isCopy: false,
  isDoubleFaced: false,
  isTransformed: false,
  isFaceDown: false,
  isBestowed: false,
  phasedOut: false,
  exerted: false,
  isRingBearer: false,
  attachmentIds: [],
  isMadnessExiled: false,
  isPlotted: false,
  isWarpExiled: false,
  foil: false,
  wouldDieInCombat: false,
};
