function soundAsset(name: string) {
  return { alias: `sound-cue.${name}`, src: `/sounds/${name}.wav` } as const;
}

export const SOUND_ASSETS = {
  gameStart: soundAsset("game-start"),
  turnStart: soundAsset("turn-start"),
  cardPlay: soundAsset("card-play"),
  cardDraw: soundAsset("card-draw"),
  cardTap: soundAsset("card-tap"),
  cardUntap: soundAsset("card-untap"),
  cardDiscard: soundAsset("card-discard"),
  cardDestroy: soundAsset("card-destroy"),
  cardExile: soundAsset("card-exile"),
  shuffle: soundAsset("shuffle"),
  lifeGain: soundAsset("life-gain"),
  lifeLoss: soundAsset("life-loss"),
  diceRoll: soundAsset("dice-roll"),
  prompt: soundAsset("prompt"),
  error: soundAsset("error"),
  counterAdd: soundAsset("counter-add"),
  combatBlock: soundAsset("combat-block"),
  cardDamage: soundAsset("card-damage"),
  daytime: soundAsset("daytime"),
  turnEnd: soundAsset("turn-end"),
  cardAttach: soundAsset("card-attach"),
  cardTransform: soundAsset("card-transform"),
  coinFlip: soundAsset("coin-flip"),
  gameLoss: soundAsset("game-loss"),
  manaBurn: soundAsset("mana-burn"),
  nighttime: soundAsset("nighttime"),
  cardPhase: soundAsset("card-phase"),
  poison: soundAsset("poison"),
  cardRegenerate: soundAsset("card-regenerate"),
  counterRemove: soundAsset("counter-remove"),
  cardSacrifice: soundAsset("card-sacrifice"),
  snapshotRestored: soundAsset("snapshot-restored"),
  speedUp: soundAsset("speed-up"),
  sprocket: soundAsset("sprocket"),
  playerShard: soundAsset("player-shard"),
  tokenCreate: soundAsset("token-create"),
  gameWin: soundAsset("game-win"),
  spellArtifact: soundAsset("spell-artifact"),
  spellArtifactCreature: soundAsset("spell-artifact-creature"),
  spellCreature: soundAsset("spell-creature"),
  spellEnchantment: soundAsset("spell-enchantment"),
  spellInstant: soundAsset("spell-instant"),
  spellPlaneswalker: soundAsset("spell-planeswalker"),
  spellSorcery: soundAsset("spell-sorcery"),
  landBlack: soundAsset("land-black"),
  landBlue: soundAsset("land-blue"),
  landGreen: soundAsset("land-green"),
  landRed: soundAsset("land-red"),
  landWhite: soundAsset("land-white"),
  landBlackRed: soundAsset("land-black-red"),
  landBlackWhite: soundAsset("land-black-white"),
  landBlueBlack: soundAsset("land-blue-black"),
  landGreenBlack: soundAsset("land-green-black"),
  landGreenBlue: soundAsset("land-green-blue"),
  landGreenRed: soundAsset("land-green-red"),
  landRedBlue: soundAsset("land-red-blue"),
  landWhiteBlue: soundAsset("land-white-blue"),
  landWhiteGreen: soundAsset("land-white-green"),
  landWhiteRed: soundAsset("land-white-red"),
  landBlackRedGreen: soundAsset("land-black-red-green"),
  landBlackWhiteGreen: soundAsset("land-black-white-green"),
  landBlueBlackRed: soundAsset("land-blue-black-red"),
  landGreenBlackBlue: soundAsset("land-green-black-blue"),
  landGreenBlueRed: soundAsset("land-green-blue-red"),
  landGreenRedWhite: soundAsset("land-green-red-white"),
  landRedBlueWhite: soundAsset("land-red-blue-white"),
  landWhiteBlueBlack: soundAsset("land-white-blue-black"),
  landWhiteGreenBlue: soundAsset("land-white-green-blue"),
  landWhiteRedBlack: soundAsset("land-white-red-black"),
  landOther: soundAsset("land-other"),
  scriptedEffect: soundAsset("scripted-effect"),
  buttonPress: soundAsset("button-press"),
  coinsDrop: soundAsset("coins-drop"),
} as const;

export type SoundAssetKey = keyof typeof SOUND_ASSETS;

export interface SoundCueDefinition {
  variants: readonly SoundAssetKey[];
  voiceLimit: number;
  cooldownMs: number;
  volume: number;
}

function cue(
  asset: SoundAssetKey,
  voiceLimit: number,
  cooldownMs: number,
  volume: number,
): SoundCueDefinition {
  return { variants: [asset], voiceLimit, cooldownMs, volume };
}

export const SOUND_CUES: Record<string, SoundCueDefinition> = {
  "game.card.draw": cue("cardDraw", 4, 40, 0.7),
  "game.card.play": cue("cardPlay", 3, 70, 0.8),
  "game.card.tap": cue("cardTap", 4, 35, 0.65),
  "game.card.untap": cue("cardUntap", 4, 35, 0.65),
  "game.card.discard": cue("cardDiscard", 3, 70, 0.75),
  "game.card.destroy": cue("cardDestroy", 3, 80, 0.8),
  "game.card.exile": cue("cardExile", 3, 80, 0.75),
  "game.library.shuffle": cue("shuffle", 1, 300, 0.65),
  "game.player.life-gain": cue("lifeGain", 3, 80, 0.7),
  "game.player.life-loss": cue("lifeLoss", 3, 80, 0.75),
  "game.turn.start": cue("turnStart", 1, 250, 0.75),
  "game.random.die-roll": cue("diceRoll", 2, 120, 0.7),
  "game.start": cue("gameStart", 1, 500, 0.8),
  "prompt.decision-required": cue("prompt", 1, 250, 0.65),
  "prompt.target-required": cue("prompt", 1, 250, 0.65),
  "prompt.payment-required": cue("prompt", 1, 250, 0.65),
  "prompt.combat-required": cue("prompt", 1, 250, 0.65),
  "prompt.action-rejected": cue("error", 1, 250, 0.75),
  "game.card.counter-add": cue("counterAdd", 3, 70, 0.7),
  "game.combat.block": cue("combatBlock", 3, 70, 0.7),
  "game.card.damage": cue("cardDamage", 3, 70, 0.7),
  "game.day-night.day": cue("daytime", 3, 70, 0.7),
  "game.turn.end": cue("turnEnd", 1, 250, 0.75),
  "game.card.attach": cue("cardAttach", 3, 70, 0.7),
  "game.card.transform": cue("cardTransform", 3, 70, 0.7),
  "game.random.coin-flip": cue("coinFlip", 3, 70, 0.7),
  "game.outcome.loss": cue("gameLoss", 1, 500, 0.8),
  "game.player.mana-burn": cue("manaBurn", 3, 70, 0.7),
  "game.day-night.night": cue("nighttime", 3, 70, 0.7),
  "game.card.phase": cue("cardPhase", 3, 70, 0.7),
  "game.player.poison": cue("poison", 3, 70, 0.7),
  "game.card.regenerate": cue("cardRegenerate", 3, 70, 0.7),
  "game.card.counter-remove": cue("counterRemove", 3, 70, 0.7),
  "game.card.sacrifice": cue("cardSacrifice", 3, 70, 0.7),
  "game.snapshot.restored": cue("snapshotRestored", 1, 250, 0.75),
  "game.player.speed-up": cue("speedUp", 1, 250, 0.75),
  "game.contraption.sprocket": cue("sprocket", 3, 70, 0.7),
  "game.player.shard": cue("playerShard", 3, 70, 0.7),
  "game.token.create": cue("tokenCreate", 3, 70, 0.7),
  "game.outcome.win": cue("gameWin", 1, 500, 0.8),
  "game.spell.resolve.artifact": cue("spellArtifact", 3, 80, 0.75),
  "game.spell.resolve.artifact-creature": cue("spellArtifactCreature", 3, 80, 0.75),
  "game.spell.resolve.creature": cue("spellCreature", 3, 80, 0.75),
  "game.spell.resolve.enchantment": cue("spellEnchantment", 3, 80, 0.75),
  "game.spell.resolve.instant": cue("spellInstant", 3, 80, 0.75),
  "game.spell.resolve.planeswalker": cue("spellPlaneswalker", 3, 80, 0.75),
  "game.spell.resolve.sorcery": cue("spellSorcery", 3, 80, 0.75),
  "game.land.enter.black": cue("landBlack", 3, 70, 0.65),
  "game.land.enter.blue": cue("landBlue", 3, 70, 0.65),
  "game.land.enter.green": cue("landGreen", 3, 70, 0.65),
  "game.land.enter.red": cue("landRed", 3, 70, 0.65),
  "game.land.enter.white": cue("landWhite", 3, 70, 0.65),
  "game.land.enter.black-red": cue("landBlackRed", 3, 70, 0.65),
  "game.land.enter.black-white": cue("landBlackWhite", 3, 70, 0.65),
  "game.land.enter.blue-black": cue("landBlueBlack", 3, 70, 0.65),
  "game.land.enter.green-black": cue("landGreenBlack", 3, 70, 0.65),
  "game.land.enter.green-blue": cue("landGreenBlue", 3, 70, 0.65),
  "game.land.enter.green-red": cue("landGreenRed", 3, 70, 0.65),
  "game.land.enter.red-blue": cue("landRedBlue", 3, 70, 0.65),
  "game.land.enter.white-blue": cue("landWhiteBlue", 3, 70, 0.65),
  "game.land.enter.white-green": cue("landWhiteGreen", 3, 70, 0.65),
  "game.land.enter.white-red": cue("landWhiteRed", 3, 70, 0.65),
  "game.land.enter.black-red-green": cue("landBlackRedGreen", 3, 70, 0.65),
  "game.land.enter.black-white-green": cue("landBlackWhiteGreen", 3, 70, 0.65),
  "game.land.enter.blue-black-red": cue("landBlueBlackRed", 3, 70, 0.65),
  "game.land.enter.green-black-blue": cue("landGreenBlackBlue", 3, 70, 0.65),
  "game.land.enter.green-blue-red": cue("landGreenBlueRed", 3, 70, 0.65),
  "game.land.enter.green-red-white": cue("landGreenRedWhite", 3, 70, 0.65),
  "game.land.enter.red-blue-white": cue("landRedBlueWhite", 3, 70, 0.65),
  "game.land.enter.white-blue-black": cue("landWhiteBlueBlack", 3, 70, 0.65),
  "game.land.enter.white-green-blue": cue("landWhiteGreenBlue", 3, 70, 0.65),
  "game.land.enter.white-red-black": cue("landWhiteRedBlack", 3, 70, 0.65),
  "game.land.enter.other": cue("landOther", 3, 70, 0.65),
  "game.card.scripted-effect": cue("scriptedEffect", 3, 70, 0.7),
  "ui.button.press": cue("buttonPress", 1, 40, 0.55),
  "adventure.coins.drop": cue("coinsDrop", 2, 100, 0.65),
};
