// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaymatSettings } from "../game/index";
import type { TokenScript } from "../token";

export type CardBackFaceSummary = {
  name: string;
  manaCost: string;
  typeLine: string;
  oracleText: string;
  uris: CardImageUris;
};

export type CardImageUris = {
  small: string;
  normal: string;
  large: string;
  png: string;
  art_crop: string;
  border_crop: string;
};

export type CardPart = { name: string; component: CardPartComponent };

export type CardPartComponent = "token" | "combo_piece" | "meld_part" | "meld_result";

export type Deck = {
  version?: string;
  id?: string;
  name: string;
  description?: string;
  color?: string;
  format?: DeckFormat;
  cards: Array<DeckCard>;
  sideboard: Array<DeckCard>;
  attractions?: Array<DeckCard>;
  contraptions?: Array<DeckCard>;
  schemes?: Array<DeckCard>;
  planes?: Array<DeckCard>;
  commanders?: Array<DeckCard>;
  companion?: DeckCard;
  maybeboard?: Array<DeckCard>;
  draft?: boolean;
  labels?: Array<DeckLabel>;
  customTags?: Array<string>;
  cardTags?: Record<string, Array<string>>;
  editor?: DeckEditorMetadata;
  coverCardName?: string;
  coverCardFace?: number;
  playmat?: string;
  playmatSettings?: PlaymatSettings;
  stackPositions?: Record<string, { x: number; y: number }>;
  tokens?: Array<DeckCard>;
};

export type DeckCard = {
  identity: DeckCardIdentity;
  uris: CardImageUris;
  allParts?: Array<CardPart>;
  color: string;
  colorIdentity: Array<string>;
  manaCost: string;
  cmc: number;
  types: Array<string>;
  subtypes: Array<string>;
  supertypes: Array<string>;
  keywords?: Array<string>;
  power?: string;
  toughness?: string;
  text: string;
  layout?: string;
  isDoubleFaced?: boolean;
  /**
   * Back face of a transform / modal_dfc card, captured at deck import.
   * Absent on single-faced cards and on decks saved before it existed.
   */
  backFace?: CardBackFaceSummary;
};

export type DeckCardIdentity = {
  id: string;
  name: string;
  setCode: string;
  cardNumber: string;
  oracleId?: string;
  tokenScript?: TokenScript;
  foil?: boolean;
};

export type DeckEditorCollectionFilter = "all" | "exact" | "other" | "partial" | "missing";

export type DeckEditorDestination = "main" | "side" | "maybe";

export type DeckEditorGoals = {
  minLands?: number;
  maxLands?: number;
  maxMissingCards?: number;
  maxAverageManaValue?: number;
  tagTargets?: Record<string, number>;
};

export type DeckEditorGroup = {
  id: string;
  name: string;
  cardNames: Array<string>;
  collapsed?: boolean;
  pinned?: boolean;
};

export type DeckEditorGroupBy = "type" | "cmc" | "color" | "custom";

export type DeckEditorLayout = {
  id: string;
  name: string;
  groupBy: DeckEditorGroupBy;
  sortBy: DeckEditorSortBy;
  groups: Array<DeckEditorGroup>;
  filter?: string;
  cardSize?: number;
  viewMode?: DeckEditorViewMode;
  collectionFilter?: DeckEditorCollectionFilter;
  defaultDestination?: DeckEditorDestination;
};

export type DeckEditorMetadata = {
  version: number;
  tags: Array<DeckEditorTag>;
  layouts: Array<DeckEditorLayout>;
  activeLayoutId?: string;
  sideboardPlans?: Array<DeckSideboardPlan>;
  budgetUsd?: number;
  budgetAmount?: number;
  priceProvider?: DeckPriceProvider;
  goals?: DeckEditorGoals;
  dismissedHints?: Array<string>;
  acquisition?: Record<string, "ordered" | "proxy">;
};

export type DeckEditorSortBy = "name" | "mana-value" | "quantity" | "owned" | "not-owned";

export type DeckEditorTag = { id: string; name: string; color?: string; icon?: string };

export type DeckEditorViewMode = "list" | "visual" | "stack";

export type DeckFormat =
  | "standard"
  | "pioneer"
  | "modern"
  | "legacy"
  | "vintage"
  | "pauper"
  | "commander"
  | "brawl"
  | "oathbreaker"
  | "draft"
  | "sealed";

export type DeckLabel = { name: string; color?: string };

export type DeckPriceProvider = "tcgplayer" | "cardmarket" | "cardhoarder";

export type DeckSideboardPlan = {
  id: string;
  matchup: string;
  bringIn: string;
  takeOut: string;
  notes: string;
};
