// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deck } from "../deck/index";
import type { EngineKind } from "../game/index";
import type { GameFormat } from "../game/index";

export type ClientPlatform = "web" | "pwa" | "desktop" | "mobile" | "unknown";

export type DraftConfig = {
  set_code?: string;
  cube_id?: string;
  cube_name?: string;
  rounds: number;
  picks_per_pass: number;
  seed?: number;
  fill_with_bots: boolean;
};

export type PlayerDeckInfo = {
  username: string;
  deck_name: string;
  deck: Deck;
  published_deck_id?: string;
  commander_name?: string;
  avatar_url?: string;
};

export type ResumeRoomRequest = {
  room_id: string;
  resume_token: string;
  room_name: string;
  max_players: number;
  format: GameFormat;
  hosted: boolean;
  engine: EngineKind;
  official_key?: string;
  password?: string;
  reconnect_timeout_s?: number;
  draft_config?: DraftConfig;
  sealed_config?: SealedConfig;
  player_order: Array<string>;
  player_decks: Array<PlayerDeckInfo>;
  starting_life: number;
  bot_players: Array<string>;
  game_id: string;
};

export type SealedConfig = {
  set_code?: string;
  cube_id?: string;
  cube_name?: string;
  singleton: boolean;
  num_boosters: number;
  base_seed?: number;
};
