use std::collections::HashMap;
use std::sync::OnceLock;

use bitflags::bitflags;

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub struct Roles: u32 {
        const REMOVAL = 1;
        const SWEEPER = 1 << 1;
        const COUNTERSPELL = 1 << 2;
        const BURN = 1 << 3;
        const DRAW = 1 << 4;
        const CANTRIP = 1 << 5;
        const MANA_DORK = 1 << 6;
        const RAMP = 1 << 7;
        const LAND_FETCH = 1 << 8;
        const RITUAL = 1 << 9;
        const COMBAT_PUMP = 1 << 10;
        const MASS_PUMP = 1 << 11;
        const ANTHEM = 1 << 12;
        const TOKENS = 1 << 13;
        const EVASIVE = 1 << 14;
        const HASTE = 1 << 15;
        const EQUIPMENT = 1 << 16;
        const REANIMATION = 1 << 17;
    }
}

// Generated by phase-ai's structural detectors over the card pool: one line
// per card, `name<TAB>role,role`, lowercase front-face names.
const TABLE: &str = include_str!("../../../card_roles.tsv");

static ROLES: OnceLock<HashMap<&'static str, Roles>> = OnceLock::new();

fn parse(role: &str) -> Roles {
    match role {
        "removal" => Roles::REMOVAL,
        "sweeper" => Roles::SWEEPER,
        "counterspell" => Roles::COUNTERSPELL,
        "burn" => Roles::BURN,
        "draw" => Roles::DRAW,
        "cantrip" => Roles::CANTRIP,
        "mana_dork" => Roles::MANA_DORK,
        "ramp" => Roles::RAMP,
        "land_fetch" => Roles::LAND_FETCH,
        "ritual" => Roles::RITUAL,
        "combat_pump" => Roles::COMBAT_PUMP,
        "mass_pump" => Roles::MASS_PUMP,
        "anthem" => Roles::ANTHEM,
        "tokens" => Roles::TOKENS,
        "evasive" => Roles::EVASIVE,
        "haste" => Roles::HASTE,
        "equipment" => Roles::EQUIPMENT,
        "reanimation" => Roles::REANIMATION,
        _ => Roles::empty(),
    }
}

pub fn lookup(name: &str) -> Roles {
    let table = ROLES.get_or_init(|| {
        TABLE
            .lines()
            .filter_map(|line| {
                let (name, roles) = line.split_once('\t')?;
                Some((
                    name,
                    roles
                        .split(',')
                        .map(parse)
                        .fold(Roles::empty(), |a, b| a | b),
                ))
            })
            .collect()
    });
    let front = name
        .split(" // ")
        .next()
        .unwrap_or(name)
        .to_ascii_lowercase();
    table.get(front.as_str()).copied().unwrap_or(Roles::empty())
}
