// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deck } from "../deck/index";

export type DraftConfig = {
  set_code?: string;
  cube_id?: string;
  cube_name?: string;
  rounds: number;
  picks_per_pass: number;
  seed?: number;
  fill_with_bots: boolean;
};

export type EngineKind = "Manabrew" | "Forge";

export type GameFormat =
  | "Any"
  | "Standard"
  | "Pioneer"
  | "Modern"
  | "Legacy"
  | "Vintage"
  | "Pauper"
  | "Commander"
  | "Brawl"
  | "Oathbreaker"
  | "Draft"
  | "Sealed";

export type PlayerDeckInfo = {
  username: string;
  deck_name: string;
  deck: Deck;
  commander_name?: string;
  avatar?: string;
};

export type ResumeRoomRequest = {
  room_id: string;
  resume_token: string;
  room_name: string;
  max_players: number;
  format: GameFormat;
  hosted: boolean;
  engine: EngineKind;
  official_key?: string;
  password?: string;
  reconnect_timeout_s?: number;
  draft_config?: DraftConfig;
  sealed_config?: SealedConfig;
  player_order: Array<string>;
  player_decks: Array<PlayerDeckInfo>;
  starting_life: number;
  bot_players: Array<string>;
};

export type SealedConfig = { set_code: string; num_boosters: number; base_seed?: number };
