apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Events
    uid: events-sqlite
    type: frser-sqlite-datasource
    jsonData:
      path: /var/manabrew/events/events.db
