// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptPresentation } from "./common";

export type ChooseBooleanInput = {
  presentation: PromptPresentation;
  confirmLabel: string;
  denyLabel: string;
};

export type ChooseBooleanOutput = { type: "decision"; value: boolean };
