// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttackAssignment } from "./common";
import type { AttackTargetDto } from "./common";

export type AttackerOptionDto = {
  attackerId: string;
  validTargetIds: Array<string>;
  mustAttack: boolean;
};

export type ChooseAttackersInput = {
  attackers: Array<AttackerOptionDto>;
  attackTargets: Array<AttackTargetDto>;
};

export type ChooseAttackersOutput = {
  type: "declareAttackers";
  assignments: Array<AttackAssignment>;
};
