// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailableAction } from "./common";

export type ChooseActionInput = { actions: Array<AvailableAction> };

export type ChooseActionOutput =
  | { type: "pass"; until?: PassUntil }
  | { type: "restoreSnapshot"; checkpointId: number }
  | { type: "act"; actionId: string };

export type PassUntil = { playerId: string; phase: string };
