// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { PromptPresentation } from "./common";

export type ChooseCardsInput = {
  presentation: PromptPresentation;
  cards: Array<CardDto>;
  min: number;
  max: number;
};

export type ChooseCardsOutput = { type: "chooseCardsDecision"; chosenCardIds: Array<string> };
