// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptPresentation } from "./common";

export type ChooseFromSelectionInput = {
  presentation: PromptPresentation;
  options: Array<string>;
  minChoices: number;
  maxChoices: number;
};

export type ChooseFromSelectionOutput = { type: "selectionDecision"; chosenIndices: Array<number> };
