// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptPresentation } from "./common";

export type ChooseNumberInput = { presentation: PromptPresentation; min: number; max: number };

export type ChooseNumberOutput = { type: "numberDecision"; chosenNumber: number | null };
