// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombatDamageAssignmentEntry } from "./common";

export type ChooseCombatDamageAssignmentInput = {
  attackerId: string;
  blockerIds: Array<string>;
  defenderId?: string;
  totalDamage: number;
  attackerHasDeathtouch: boolean;
};

export type ChooseCombatDamageAssignmentOutput = {
  type: "combatDamageAssignmentDecision";
  assignments: Array<CombatDamageAssignmentEntry>;
};
