// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";

export type ChooseDamageAssignmentOrderInput = {
  attackerId: string;
  blockerIds: Array<string>;
  blockerCards: Array<CardDto>;
};

export type ChooseDamageAssignmentOrderOutput = {
  type: "damageAssignmentOrderDecision";
  orderedBlockerIds: Array<string>;
};
