// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetRef } from "./common";
import type { TargetingIntent } from "../game/index";

export type ChooseBoardTargetsInput = {
  candidates: Array<TargetRef>;
  hostile: boolean;
  intent: TargetingIntent;
  minTargets: number;
  maxTargets: number;
  chosenTargets: number;
  label: string;
};

export type ChooseBoardTargetsOutput = { type: "boardTargets"; chosen: Array<TargetRef> };
