// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockAssignment } from "./common";

export type BlockableAttackerDto = {
  attackerId: string;
  validBlockerIds: Array<string>;
  minBlockers: number;
  maxBlockers?: number;
  mustBeBlocked: boolean;
};

export type ChooseBlockersInput = {
  attackers: Array<BlockableAttackerDto>;
  availableBlockerIds: Array<string>;
  error?: string;
};

export type ChooseBlockersOutput = { type: "declareBlockers"; assignments: Array<BlockAssignment> };
