// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetingIntent } from "../game/index";

export type ActivatableAbilityInfo = {
  cardId: string;
  abilityIndex: number;
  description: string;
  isManaAbility: boolean;
  cost?: string;
  producedMana?: Array<Mana>;
};

export type AttackAssignment = { attackerId: string; targetId: string };

export type AttackTargetDto = { id: string; label: string; kind: AttackTargetKind };

export type AttackTargetKind = "player" | "planeswalker" | "battle";

export type AvailableAction = { id: string } & (
  | { type: "cast"; cardId: string; mode: string; modeLabel: string }
  | ({ type: "activateAbility" } & ActivatableAbilityInfo)
  | { type: "undoMana"; cardId: string }
  | { type: "delve"; cardId: string }
  | { type: "undelve"; cardId: string }
);

export type AvailableActionKind =
  | { type: "cast"; cardId: string; mode: string; modeLabel: string }
  | ({ type: "activateAbility" } & ActivatableAbilityInfo)
  | { type: "undoMana"; cardId: string }
  | { type: "delve"; cardId: string }
  | { type: "undelve"; cardId: string };

export type BlockAssignment = { blockerId: string; attackerId: string };

export type CombatDamageAssignmentEntry = { assigneeId: string; damage: number };

export type Mana = { color: ManaColor; amount: number };

export type ManaColor = "W" | "U" | "B" | "R" | "G" | "C";

export type PlayOptionDto = { cardId: string; mode: string; modeLabel: string };

export type PromptPresentation = {
  title: string;
  description?: string;
  text?: string;
  sourceCardId?: string;
  targets: Array<TargetRef>;
};

export type TargetAnyChoice =
  | { kind: "player"; playerId: string }
  | { kind: "card"; cardId: string }
  | { kind: "none" };

export type TargetKind = "player" | "card" | "spell";

export type TargetRef = { kind: TargetKind; id: string; intent?: TargetingIntent; oracle?: string };
