// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiceRollEntry = {
  label?: string;
  playerId?: string;
  naturalResults: Array<number>;
  finalResults: Array<number>;
  ignoredRolls: Array<number>;
  highlighted: boolean;
};

export type DiceRolledInput = {
  sides: number;
  rolls: Array<DiceRollEntry>;
  title?: string;
  sourceCardName?: string;
};

export type DiceRolledOutput = { type: "diceRolledAcknowledged" };
