// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";

export type MulliganPutBackInput = {
  handCardIds: Array<string>;
  cards: Array<CardDto>;
  count: number;
};

export type MulliganPutBackOutput = { type: "mulliganPutBackDecision"; cardIds: Array<string> };
