// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MulliganInput = { handCardIds: Array<string>; mulliganCount: number };

export type MulliganOutput = { type: "mulliganDecision"; keep: boolean };
