// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailableAction } from "./common";

export type PayManaCostInput = {
  cardId: string;
  cardName: string;
  manaCost: string;
  canConfirmFromPool: boolean;
  actions: Array<AvailableAction>;
  description?: string;
};

export type PayManaCostOutput =
  | { type: "act"; actionId: string }
  | { type: "pay"; auto: boolean }
  | { type: "payLife" }
  | { type: "cancel" };
