// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { PromptPresentation } from "./common";

export type ReorderCardsInput = {
  presentation: PromptPresentation;
  cards: Array<CardDto>;
  targetLabel: string;
  topOfDeck: boolean;
};

export type ReorderCardsOutput = { type: "reorderDecision"; orderedCardIds: Array<string> };
