// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";

export type RevealCardsInput = {
  cards: Array<CardDto>;
  zone: string;
  ownerPlayerId: string;
  message: string;
};

export type RevealCardsOutput = { type: "revealCardsAcknowledged" };
