// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDto } from "../game/index";
import type { PromptPresentation } from "./common";

export type ScryDestination = "libraryTop" | "libraryBottom" | "graveyard" | "exile" | "hand";

export type ScryInput = {
  presentation: PromptPresentation;
  cards: Array<CardDto>;
  zones: Array<ScryDestination>;
};

export type ScryOutput = { type: "scryDecision"; zoneCardIds: Array<Array<string>> };
