// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineKind = "Manabrew" | "Forge" | "Ironsmith";

export type GameFormat =
  | "Any"
  | "Standard"
  | "Pioneer"
  | "Modern"
  | "Legacy"
  | "Vintage"
  | "Pauper"
  | "Commander"
  | "Brawl"
  | "Oathbreaker"
  | "Draft"
  | "Sealed";

export type PlaymatSettings = {
  opacity?: number;
  texture?: number;
  borderWidth?: number;
  borderColor?: string;
  fit?: string;
  offsetX?: number;
  offsetY?: number;
  zoom?: number;
  blur?: number;
  brightness?: number;
  color?: string;
};
