import type { ThemePreset } from "./presets";
import { buildGameColors, type BasePalette } from "./buildGameColors";

const primary = "#f27633";
const secondary = "#ffe7d5";

const palette: BasePalette = {
  foreground: "#ffffff",
  labelMuted: "#bd8ca8",
  labelGhost: "#d8bbcb",
  placeholderFill: "#1b151f",
  placeholderStroke: "#5b3f66",
  canvasBackground: "#0e0c12",
  red: "#c93d50",
  redDeep: "#a92f46",
  orange: "#e87828",
  amber: "#b99a62",
  yellow: "#d8d34a",
  green: "#75b454",
  teal: "#3fb6b8",
  cyan: "#4cbfd3",
  blue: "#527fbd",
  sky: "#58abd2",
  indigo: "#4c2769",
  violet: "#a85fc5",
  purple: "#71379b",
  pink: "#ce5d82",
  slate: "#927483",
  brown: "#ad6848",
  paper: "#efc28f",
  poison: "#82ad41",
  promptDefense: "#4f9fd0",
  manaW: "#f8f6d8",
  manaU: "#c1d7e9",
  manaB: "#cac5c0",
  manaR: "#e49977",
  manaG: "#a3c095",
  manaC: "#cac5c0",
};

const preset: ThemePreset = {
  id: "default",
  name: "Manabrew",
  description: "Manabrew default theme",
  light: {
    background: "#f4f2e7",
    foreground: "#29262a",
    card: "#fffdf7",
    "card-foreground": "#29262a",
    popover: "#fffdf7",
    "popover-foreground": "#29262a",
    primary,
    "primary-foreground": "#111214",
    secondary,
    "secondary-foreground": "#111214",
    muted: "#efe5dc",
    "muted-foreground": "#665d61",
    accent: secondary,
    "accent-foreground": "#111214",
    destructive: "#c93d50",
    "destructive-foreground": "#fffdf7",
    border: "#c9b7c8",
    input: "#d8cbd9",
    ring: primary,
    selection: "#71379b",
    "selection-foreground": "#fffdf7",
    commander: "#c89317",
    warning: "#806000",
    overlay: "#000000",
  },
  dark: {
    background: "#111214",
    foreground: "#fffaf5",
    card: "#1b191d",
    "card-foreground": "#fffaf5",
    popover: "#221f24",
    "popover-foreground": "#fffaf5",
    primary,
    "primary-foreground": "#111214",
    secondary,
    "secondary-foreground": "#111214",
    muted: "#2d282e",
    "muted-foreground": "#bbaeb2",
    accent: secondary,
    "accent-foreground": "#111214",
    destructive: "#c93d50",
    "destructive-foreground": "#fffaf5",
    border: "#4a3b4d",
    input: "#352d38",
    ring: primary,
    selection: "#71379b",
    "selection-foreground": "#ffffff",
    commander: "#f1c84b",
    warning: "#c99700",
    overlay: "#000000",
  },
  gameColors: {
    ...buildGameColors(palette),
    cardRing: primary,
    "activeAction.active": primary,
    "playerColors.self": palette.green,
    "playerColors.opponent1": palette.blue,
    "playerColors.opponent2": palette.yellow,
    "playerColors.opponent3": palette.pink,
    "phaseStrip.background": "#221f24",
  },
  gameFontSizes: {
    badgeCount: "13px",
    life: "14px",
    manaCount: "11px",
    zoneCount: "14px",
    zoneLabel: "10px",
    avatarInitials: "16px",
  },
};

export default preset;
