import type { ThemeColors } from "@/themes/appTheme";
import type { GameThemeColorKey } from "@/themes/gameTheme";

type AppThemeKey = keyof ThemeColors;
export const APP_THEME_COLOR_DESCRIPTIONS: Record<AppThemeKey, string> = {
  background: "Page / window background fill.",
  foreground: "Default body text colour.",
  card: "Surface colour for cards, panels, and solid containers.",
  "card-foreground": "Text colour placed on `card` surfaces.",
  popover: "Background of popovers, menus, and floating panels.",
  "popover-foreground": "Text colour inside popovers.",
  primary: "Primary action colour — main call-to-action buttons, links, active chip fills.",
  "primary-foreground": "Text / icons placed on a `primary` background.",
  secondary: "Secondary / subtle button background.",
  "secondary-foreground": "Text on secondary-style buttons.",
  muted: "Muted surface for low-priority regions.",
  "muted-foreground": "Captions, hints, and secondary text colour.",
  accent: "Hover / active highlight surface.",
  "accent-foreground": "Text on accent surfaces.",
  destructive: "Destructive actions, errors, and deny states.",
  "destructive-foreground": "Text placed on `destructive` buttons.",
  border: "Default border and divider lines.",
  input: "Form input borders and backgrounds.",
  ring: "Focus ring around interactive elements.",
  selection: "Background of selected text.",
  "selection-foreground": "Colour of selected text itself.",
  commander: "Commander indicator (crown icon, commander panel accent).",
  warning: "Warning states and soft cautions.",
  overlay: "Modal / dialog backdrop dim.",
};

export const GAME_THEME_COLOR_DESCRIPTIONS: Partial<Record<GameThemeColorKey, string>> = {
  "activeAction.priority": "Highlight surrounding the player who currently has priority.",
  "activeAction.active": "Active-turn ring, turn-text colour, and general 'your turn' cue.",
  "promptAction.passAction": "Pass priority / pass turn button fill.",
  "promptAction.attackAction": "Declare-attackers button fill.",
  "promptAction.defenseAction": "Defense / declare-blockers button fill.",
  "promptAction.cancel": "Cancel / decline button fill.",
  "promptForeground.passAction": "Text and icons on pass and continue actions.",
  "promptForeground.attackAction": "Text and icons on attack actions.",
  "promptForeground.defenseAction": "Text and icons on defense actions.",
  "promptForeground.cancel": "Text and icons on cancel actions.",
  "interaction.untap": "An available untap action, separate from cancellation.",
  "connection.disconnected": "A disconnected player's connection indicator.",
  "zone.library": "Library zone accent.",
  "zone.graveyard": "Graveyard zone accent.",
  "zone.exile": "Exile zone accent.",
  "zone.command": "Command zone accent.",
  "cardStatus.summoningSick": "A creature that cannot attack or use tap abilities yet.",
  cardSelection: "Persistent card selection, distinct from availability or hostile targeting.",
  "arrow.attack": "Attacker arrow from attacker to defender.",
  "arrow.block": "Blocker arrow from blocker to attacker.",
  "arrow.hostileTarget": "A hostile spell or ability targeting a card or player.",
  "arrow.friendlyTarget": "A supportive spell or ability targeting a card or player.",
  "pointer.hostile": "Hostile targeting, such as damage, destruction, exile, or countering.",
  "pointer.friendly":
    "Glow around the cursor for friendly / supportive targeting — buff, heal, draw, reveal, untap, attach, copy.",
  "mana.W": "White mana pip and dual-land tap-button tint.",
  "mana.U": "Blue mana pip and dual-land tap-button tint.",
  "mana.B": "Black mana pip and dual-land tap-button tint.",
  "mana.R": "Red mana pip and dual-land tap-button tint.",
  "mana.G": "Green mana pip and dual-land tap-button tint.",
  "mana.C": "Colorless mana pip and tap-button tint.",
  "cardStatus.exerted": "Badge colour for exerted creatures (won't untap).",
  "cardStatus.morph": "Badge for face-down / morph creatures.",
  "cardStatus.bestow": "Badge for bestowed auras.",
  "cardStatus.token": "Badge for token creatures.",
  "cardStatus.transformed": "Badge for transformed double-faced cards.",
  "cardStatus.plotted": "Badge for plotted cards in exile.",
  "cardStatus.madness": "Badge for madness-exiled cards.",
  "cardStatus.warped": "Badge for warp-exiled cards.",
  "cardStatus.copy": "Badge for permanents that are copies of another card.",
  "counter.default": "Fallback chip colour for unknown counter types.",
  "counter.p1p1": "+1/+1 counter chip.",
  "counter.m1m1": "-1/-1 counter chip.",
  "counter.loyalty": "Loyalty counter chip (planeswalkers).",
  "counter.charge": "Charge counter chip.",
  "counter.quest": "Quest counter chip.",
  "counter.study": "Study counter chip.",
  "counter.lore": "Lore counter chip (sagas).",
  "counter.age": "Age counter chip.",
  "counter.time": "Time counter chip (suspend, etc.).",
  "counter.fade": "Fade counter chip.",
  "counter.level": "Level counter chip (level-up creatures).",
  "counter.storage": "Storage counter chip.",
  "counter.mining": "Mining counter chip.",
  "counter.brick": "Brick counter chip.",
  "counter.depletion": "Depletion counter chip.",
  "counter.page": "Page counter chip (book rooms).",
  "pt.neutral": "P/T badge when stats match the printed base.",
  "pt.lethal": "P/T badge when incoming damage would be lethal.",
  "pt.buffed": "P/T badge when stats are above the printed base.",
  "pt.debuffed": "P/T badge when stats are below the printed base.",
  success: "Positive states — connected, saved, victory banner, good FPS.",
  poison: "Poison counter / skull icon — MTG infect-green.",
  life: "Life total / heart icon.",
  "canvas.background": "Pixi canvas table background fill.",
  "canvas.shadow": "Drop-shadow ink (almost always black).",
  "canvas.neutral": "High-contrast stroke / outline colour for arrows and icons.",
  "phaseStrip.background": "Raised charcoal surface behind phase-strip cells.",
  "cardPlaceholder.fill": "Loading-state card sprite fill.",
  "cardPlaceholder.stroke": "Loading-state card sprite border.",
  textOnTinted: "Text colour placed on tinted chips and badges.",
  textMuted: "Subdued label colour on empty-zone placeholders.",
  textGhost: "Ghost card-name colour shown while art loads.",
  cardRing: "Available actions, playable cards, and transient hover feedback.",
};
export const APP_THEME_COLOR_LABELS: Record<AppThemeKey, string> = {
  background: "Background",
  foreground: "Text",
  card: "Card Surface",
  "card-foreground": "Card Text",
  popover: "Popover Surface",
  "popover-foreground": "Popover Text",
  primary: "Primary",
  "primary-foreground": "Primary Text",
  secondary: "Secondary",
  "secondary-foreground": "Secondary Text",
  muted: "Muted Surface",
  "muted-foreground": "Muted Text",
  accent: "Accent",
  "accent-foreground": "Accent Text",
  destructive: "Destructive",
  "destructive-foreground": "Destructive Text",
  border: "Border",
  input: "Input",
  ring: "Focus Ring",
  selection: "Selection",
  "selection-foreground": "Selection Text",
  commander: "Commander",
  warning: "Warning",
  overlay: "Overlay",
};

export const APP_THEME_GROUPS: { heading: string; description: string; keys: AppThemeKey[] }[] = [
  {
    heading: "Surfaces & Foregrounds",
    description: "Neutral page, card, and popover backgrounds plus their paired text colours.",
    keys: ["background", "foreground", "card", "card-foreground", "popover", "popover-foreground"],
  },
  {
    heading: "Brand & Accent",
    description: "Primary action colour and the softer accent / secondary tints.",
    keys: [
      "primary",
      "primary-foreground",
      "secondary",
      "secondary-foreground",
      "accent",
      "accent-foreground",
    ],
  },
  {
    heading: "State Signals",
    description: "Destructive, warning, commander, and selection highlights.",
    keys: [
      "destructive",
      "destructive-foreground",
      "warning",
      "commander",
      "selection",
      "selection-foreground",
    ],
  },
  {
    heading: "Muted & Structure",
    description: "Subdued surfaces, borders, input fields, focus ring, and overlay dim.",
    keys: ["muted", "muted-foreground", "border", "input", "ring", "overlay"],
  },
];

export const GAME_THEME_GROUPS: {
  heading: string;
  description: string;
  prefixes?: string[];
  exactKeys?: string[];
}[] = [
  {
    heading: "Active Action",
    description: "Priority ring, turn glow, and related active-state cues.",
    prefixes: ["activeAction."],
  },
  {
    heading: "Prompt Buttons",
    description: "Pass, attack, defense, cancel, and related prompt action buttons.",
    prefixes: ["promptAction.", "promptForeground."],
  },
  {
    heading: "Combat & Placement Arrows",
    description: "Curved arrows for attack / block declarations and the placement ghost.",
    prefixes: ["arrow."],
  },
  {
    heading: "Targeting Pointers",
    description: "Per-intent pointer icon glow (sacrifice, destroy, exile, bounce, tap …).",
    prefixes: ["pointer."],
  },
  {
    heading: "Selection & interaction",
    description: "Persistent choices and available actions, independent of targeting intent.",
    exactKeys: ["cardSelection", "cardRing"],
    prefixes: ["interaction."],
  },
  {
    heading: "Zones & connection",
    description: "Zone identity and connection state, independent of mechanics and cancellation.",
    prefixes: ["zone.", "connection."],
  },
  {
    heading: "Mana Symbols",
    description: "W / U / B / R / G / C pip and tap-button tints.",
    prefixes: ["mana."],
  },
  {
    heading: "Card Status Badges",
    description: "Exerted, morph, bestow, token, transformed, plotted, madness, warped.",
    prefixes: ["cardStatus."],
  },
  {
    heading: "Counters",
    description: "Per-counter-type chip colour (P1P1, M1M1, Loyalty, Charge …).",
    prefixes: ["counter."],
  },
  {
    heading: "P / T Badge",
    description: "Neutral / lethal / buffed / debuffed stat-badge backgrounds.",
    prefixes: ["pt."],
  },
  {
    heading: "Status Signals",
    description: "Generic UI states: success (connected / win), poison counter, life / heart.",
    exactKeys: ["success", "poison", "life"],
  },
  {
    heading: "Canvas",
    description: "Pixi table background, shadow ink, and high-contrast neutral.",
    prefixes: ["canvas."],
  },
  {
    heading: "Card Placeholder",
    description: "Sprite fill / stroke used while a card's image is loading.",
    prefixes: ["cardPlaceholder."],
  },
  {
    heading: "Text Roles",
    description: "Generic text colours on tinted chips, empty zones, and ghost placeholders.",
    exactKeys: ["textOnTinted", "textMuted", "textGhost"],
  },
  {
    heading: "Player Colours",
    description: "Per-seat colours for phase strip indicators and turn tint.",
    prefixes: ["playerColors."],
  },
  {
    heading: "Badges",
    description: "Status chip icon colours rendered next to the mana pool.",
    prefixes: ["badges."],
  },
];
