// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccessTokenResponse = { access_token: string; token_type: string; expires_in: number };

export type AuthAccount = { id: string; handle: string; handlePending: boolean; createdAt: string };

export type AuthIdentity = { provider: string; email?: string };

export type AuthProviders = { github: boolean; discord: boolean; email: boolean };

export type AuthSessionResponse = {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token: string;
  account: AuthAccount;
};

export type EmailVerifyRequest = { email: string; code: string };

export type ExchangeCodeRequest = { code: string };

export type MagicLinkRequest = { email: string };

export type MeResponse = { account: AuthAccount; identities: Array<AuthIdentity> };

export type OAuthStartRequest = { mode: string; client: string };

export type OAuthStartResponse = { authorizeUrl: string };

export type RevocationRequest = { token: string };

export type TokenRequest = { grant_type: string; refresh_token: string; resource?: string };

export type UpdateHandleRequest = { handle: string };
