// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameViewDto } from "../game/index";
import type { PromptInput } from "../prompts/promptInput";
import type { PromptOutput } from "../prompts/promptOutput";

export type AgentPrompt = {
  promptId: number;
  decidingPlayerId: string;
  sourceCardId?: string;
  input: PromptInput;
};

export type ClientToServerMessage =
  | { kind: "response"; action: PromptOutput }
  | { kind: "directive"; directive: DirectiveInput };

export type DirectiveInput = { type: "concede" };

export type StateUpdate = { gameView: GameViewDto };
