export const PREVIEW_SCENARIOS = [
  { label: "Portrait / reminder text", name: "Serra Angel" },
  { label: "Vanilla / flavor text", name: "Savannah Lions" },
  { label: "Land / mana abilities", name: "Steam Vents" },
  { label: "Artifact creature", name: "Wurmcoil Engine" },
  { label: "Planeswalker / loyalty", name: "Jace, the Mind Sculptor" },
  { label: "Saga / chapters", name: "The Eldest Reborn" },
  { label: "Class / levels", name: "Ranger Class" },
  { label: "Transform DFC", name: "Delver of Secrets" },
  { label: "Transformed DFC", name: "Delver of Secrets", back: true },
  { label: "Modal DFC", name: "Bala Ged Recovery" },
  { label: "Modal DFC / land face", name: "Bala Ged Recovery", back: true },
  { label: "Battle / landscape front", name: "Invasion of Zendikar" },
  { label: "Battle / creature back", name: "Invasion of Zendikar", back: true },
  { label: "Split / both halves", name: "Fire // Ice" },
  { label: "Aftermath / both halves", name: "Cut // Ribbons" },
  { label: "Room / both doors", name: "Roaring Furnace // Steaming Sauna" },
  { label: "Plane / landscape", name: "Academy at Tolaria West" },
  { label: "Phenomenon / landscape", name: "Spatial Merging" },
  { label: "Scheme / landscape", name: "Your Fate Is Thrice Sealed" },
  { label: "Adventure / two rules sections", name: "Brazen Borrower" },
  { label: "Flip card", name: "Budoka Gardener" },
  { label: "Prototype", name: "Phyrexian Fleshgorger" },
  { label: "Meld", name: "Bruna, the Fading Light" },
  { label: "Long rules / scrolling", name: "Questing Beast" },
  { label: "Face-down / hidden identity", name: "" },
] satisfies Array<{ label: string; name: string; back?: boolean }>;
