// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetRef } from "../prompts/common";

export type CardDto = {
  id: string;
  identity: CardIdentity;
  color: string;
  manaCost: string;
  cmc: number;
  types: Array<string>;
  subtypes: Array<string>;
  supertypes: Array<string>;
  power: string | null;
  toughness: string | null;
  basePower?: number;
  baseToughness?: number;
  text: string;
  controllerId: string;
  ownerId: string;
  zoneId: string;
  tapped: boolean;
  isCrewed: boolean;
  isAttacking: boolean;
  attackingPlayerId?: string;
  attackTargetId?: string;
  keywords: Array<string>;
  counters: Record<string, number>;
  damage: number;
  summoningSick: boolean;
  isCopy: boolean;
  isDoubleFaced: boolean;
  isTransformed: boolean;
  isFaceDown: boolean;
  isBestowed: boolean;
  phasedOut: boolean;
  exerted: boolean;
  isRingBearer: boolean;
  attachedTo?: string;
  attachmentIds: Array<string>;
  flashbackCost?: string;
  kickerCost?: string;
  effectiveManaCost?: string;
  madnessCost?: string;
  isMadnessExiled: boolean;
  isPlotted: boolean;
  isWarpExiled: boolean;
  foil: boolean;
  wouldDieInCombat: boolean;
};

export type CardIdentity = { name: string; setCode: string; cardNumber: string; isToken: boolean };

export type CombatAssignmentDto = { blockerId: string; attackerId: string };

export type GameViewDto = {
  gameId: string;
  turn: number;
  step: string;
  combatAssignments: Array<CombatAssignmentDto>;
  activePlayerId: string;
  priorityPlayerId: string;
  players: Array<PlayerDto>;
  battlefield: Array<CardDto>;
  stack: Array<StackObjectDto>;
  gameOver: boolean;
  winnerId: string | null;
  monarchId: string | null;
  initiativeHolderId: string | null;
};

export type PlayerDto = {
  id: string;
  name: string;
  status: PlayerStatus;
  isHuman: boolean;
  life: number;
  poison: number;
  hand: Array<CardDto>;
  graveyard: Array<CardDto>;
  exile: Array<CardDto>;
  commandZone: Array<CardDto>;
  libraryCount: number;
  manaPool: Record<string, number>;
  commanderDamage: Record<string, number>;
  energyCounters: number;
  radiationCounters: number;
  hasCityBlessing: boolean;
  ringLevel: number;
  speed: number;
  experienceCounters: number;
  ticketCounters: number;
};

export type PlayerStatus = "playing" | "lost" | "conceded";

export type PlaymatSettings = {
  opacity?: number;
  texture?: number;
  borderWidth?: number;
  borderColor?: string;
  fit?: string;
  offsetX?: number;
  offsetY?: number;
  zoom?: number;
  blur?: number;
  brightness?: number;
  color?: string;
};

export type StackObjectDto = {
  id: string;
  sourceId: string;
  controllerId: string;
  identity: CardIdentity;
  text: string;
  isPermanentSpell: boolean;
  isCasting: boolean;
  targets: Array<TargetRef>;
};

export type TargetingIntent =
  | "damage"
  | "destroy"
  | "sacrifice"
  | "exile"
  | "bounce"
  | "mill"
  | "discard"
  | "counter"
  | "tap"
  | "untap"
  | "copy"
  | "buff"
  | "debuff"
  | "heal"
  | "loseLife"
  | "reveal"
  | "draw"
  | "gainControl"
  | "fight"
  | "attach"
  | "attack"
  | "block"
  | "hostile"
  | "friendly";
