// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HubDeckDetail = {
  deck: Deck;
  id: string;
  name: string;
  author: string;
  description?: string;
  format?: DeckFormat;
  commanders: Array<string>;
  colors: string;
  cardCount: number;
  coverCardName?: string;
  coverImageUrl?: string;
  createdAt: string;
};

export type HubDeckList = {
  decks: Array<HubDeckSummary>;
  total: number;
  page: number;
  pageSize: number;
};

export type HubDeckSummary = {
  id: string;
  name: string;
  author: string;
  description?: string;
  format?: DeckFormat;
  commanders: Array<string>;
  colors: string;
  cardCount: number;
  coverCardName?: string;
  coverImageUrl?: string;
  createdAt: string;
};

export type PublishDeckRequest = { author: string; deck: Deck };

export type PublishDeckResponse = { id: string; managementToken: string };

export type TopDeckStat = {
  deckName: string;
  commander?: string;
  plays: number;
  lastPlayed?: string;
};
