// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaymatSettings } from "../game/index";

export type CardImageUris = {
  small: string;
  normal: string;
  large: string;
  png: string;
  art_crop: string;
  border_crop: string;
};

export type CardPart = { name: string; component: CardPartComponent };

export type CardPartComponent = "token" | "combo_piece" | "meld_part" | "meld_result";

/**
 * Mirror of `manabrew.ts:CardRulesSummary`. The engine derives most
 * of this from its own card DB; included here so the same wire shape
 * round-trips losslessly.
 */
export type CardRulesSummary = {
  color: string;
  colorIdentity: Array<string>;
  manaCost: string;
  cmc: number;
  types: Array<string>;
  subtypes: Array<string>;
  supertypes: Array<string>;
  keywords?: Array<string>;
  power?: string;
  toughness?: string;
  text: string;
  layout?: string;
  isDoubleFaced?: boolean;
};

export type Deck = {
  version?: string;
  id?: string;
  name: string;
  description?: string;
  color?: string;
  format?: DeckFormat;
  cards: Array<DeckCard>;
  sideboard: Array<DeckCard>;
  attractions?: Array<DeckCard>;
  contraptions?: Array<DeckCard>;
  schemes?: Array<DeckCard>;
  planes?: Array<DeckCard>;
  commanders?: Array<DeckCard>;
  companion?: DeckCard;
  maybeboard?: Array<DeckCard>;
  draft?: boolean;
  labels?: Array<DeckLabel>;
  coverCardName?: string;
  coverCardFace?: number;
  playmat?: string;
  playmatSettings?: PlaymatSettings;
  stackPositions?: Record<string, { x: number; y: number }>;
  tokens?: Array<DeckCard>;
};

export type DeckCard = {
  identity: DeckCardIdentity;
  uris: CardImageUris;
  allParts?: Array<CardPart>;
  color: string;
  colorIdentity: Array<string>;
  manaCost: string;
  cmc: number;
  types: Array<string>;
  subtypes: Array<string>;
  supertypes: Array<string>;
  keywords?: Array<string>;
  power?: string;
  toughness?: string;
  text: string;
  layout?: string;
  isDoubleFaced?: boolean;
};

export type DeckCardIdentity = {
  id: string;
  name: string;
  setCode: string;
  cardNumber: string;
  foil?: boolean;
};

export type DeckFormat =
  | "standard"
  | "pioneer"
  | "modern"
  | "legacy"
  | "vintage"
  | "pauper"
  | "commander"
  | "brawl"
  | "oathbreaker"
  | "draft"
  | "sealed";

export type DeckLabel = { name: string; color?: string };
