/**
 * Single source of truth for compile-time feature flags. Add a boolean here
 * (default `false` to ship a feature dark) and read it via `isFeatureEnabled`.
 * Do not scatter feature gates anywhere else.
 */
export const featureFlags = {
  // Ironsmith trusted engine/runtime. Turning this on only surfaces the engine
  // where the real WASM is actually bundled: the runtime registry and the lobby
  // tile also gate on `IRONSMITH_WASM_AVAILABLE` (generated by
  // `scripts/sync-ironsmith-wasm.mjs` — true for the built `ironsmith/pkg`,
  // false when the stub is installed because the submodule wasn't built). So a
  // build that skips the submodule ships this dark automatically, never a tile
  // backed by the throwing stub. Build it with `./ironsmith/rebuild-wasm.sh` +
  // `yarn sync:ironsmith`. Even with the flag on and the wasm bundled, the
  // engine is OFF until the user opts in via Settings (`ironsmithRuntimeEnabled`
  // preference) — the experimental engine ships dark in prod by default.
  ironsmithRuntime: true,
} as const;

export type FeatureFlag = keyof typeof featureFlags;

export function isFeatureEnabled(flag: FeatureFlag): boolean {
  return featureFlags[flag];
}
